# Generated by Django 2.0.7 on 2018-07-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180722_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_nums',
            new_name='Read_num',
        ),
    ]
