# Generated by Django 2.0.7 on 2018-07-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180722_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_num',
            new_name='ReadNum',
        ),
    ]
